name: Sync Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' &&
      github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.repo.full_name != github.repository.full_name)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript script
        run: node sync_data.js
